[build]
  functions = "netlify/functions"
  publish = "build"

[dev]
  command = "npm start" # or "yarn start" if using yarn
  targetPort = 3000  # Your frontend is running here
  port = 8888  # Netlify Dev functions will run on this port
